const products=[
{id:'welkom',name:'Zinergi Welkomstpakket',price:107.46,originalPrice:119.40,cat:'supplement',label:'Eenmalige kennismakingsset',img:'assets/products/welkomstpakket.jpg',desc:'Alle vier Zinergi supplementen in herbruikbare glazen potten, samen met de handgemaakte houten houder. Eenmalig verkrijgbaar met 10% welkomstkorting.',badge:'10% welkom'},
{id:'biotica',name:'Biotica Expert',price:39.95,cat:'supplement',label:'Darmen',img:'assets/products/biotica-glass.jpg',refillImg:'assets/products/biotica-refill.jpg',desc:'Probiotische ondersteuning voor een gevarieerd en veerkrachtig darmmicrobioom.',badge:'Bestseller',variants:true},
{id:'fiber',name:'Fiber Expert',price:32.50,cat:'supplement',label:'Darmen',img:'assets/products/fiber-glass.jpg',refillImg:'assets/products/fiber-refill.jpg',desc:'Prebiotische vezels als dagelijkse voeding voor je goede darmbacterien.',variants:true},
{id:'magnesium',name:'Magnesium Expert',price:19.95,cat:'supplement',label:'Energie & rust',img:'assets/products/magnesium-glass.jpg',refillImg:'assets/products/magnesium-refill.jpg',desc:'Ondersteunt ontspanning, spieren en een normale energiestofwisseling.',badge:'Populair',variants:true},
{id:'multi',name:'Multi Compleet',price:27,cat:'supplement',label:'Dagelijkse basis',img:'assets/products/multi-glass.jpg',refillImg:'assets/products/multi-refill.jpg',desc:'Een complete dagelijkse basis met zorgvuldig gekozen vitamines en mineralen.',variants:true},
{id:'biotica-refill',name:'Biotica Expert Navulling',price:39.95,cat:'refill',label:'Brievenbusnavulling',img:'assets/products/biotica-refill.jpg',desc:'Papieren navulzak met voedselveilige beschermfolie. Hersluitbaar en passend door de brievenbus.',badge:'Navulling'},
{id:'fiber-refill',name:'Fiber Expert Navulling',price:32.50,cat:'refill',label:'Brievenbusnavulling',img:'assets/products/fiber-refill.jpg',desc:'Papieren navulzak met voedselveilige beschermfolie. Hersluitbaar en passend door de brievenbus.',badge:'Navulling'},
{id:'magnesium-refill',name:'Magnesium Expert Navulling',price:19.95,cat:'refill',label:'Brievenbusnavulling',img:'assets/products/magnesium-refill.jpg',desc:'Papieren navulzak met voedselveilige beschermfolie. Hersluitbaar en passend door de brievenbus.',badge:'Navulling'},
{id:'multi-refill',name:'Multi Compleet Navulling',price:27,cat:'refill',label:'Brievenbusnavulling',img:'assets/products/multi-refill.jpg',desc:'Papieren navulzak met voedselveilige beschermfolie. Hersluitbaar en passend door de brievenbus.',badge:'Navulling'},
{id:'sub-biotica',parentId:'biotica',subscriptionProduct:true,name:'Biotica Expert Abonnement',price:39.95,cat:'subscription',label:'Vanaf 39,95 per levering',img:'assets/products/biotica-refill.jpg',desc:'Automatische levering van 1, 2 of 3 navullingen, afgestemd op jouw gebruik.',badge:'Abonnement'},
{id:'sub-fiber',parentId:'fiber',subscriptionProduct:true,name:'Fiber Expert Abonnement',price:32.50,cat:'subscription',label:'Vanaf 32,50 per levering',img:'assets/products/fiber-refill.jpg',desc:'Automatische levering van 1, 2 of 3 navullingen, afgestemd op jouw gebruik.',badge:'Abonnement'},
{id:'sub-magnesium',parentId:'magnesium',subscriptionProduct:true,name:'Magnesium Expert Abonnement',price:19.95,cat:'subscription',label:'Vanaf 19,95 per levering',img:'assets/products/magnesium-refill.jpg',desc:'Automatische levering van 1, 2 of 3 navullingen, afgestemd op jouw gebruik.',badge:'Abonnement'},
{id:'sub-multi',parentId:'multi',subscriptionProduct:true,name:'Multi Compleet Abonnement',price:27,cat:'subscription',label:'Vanaf 27,00 per levering',img:'assets/products/multi-refill.jpg',desc:'Automatische levering van 1, 2 of 3 navullingen, afgestemd op jouw gebruik.',badge:'Abonnement'},
{id:'sub-compleet',name:'Zinergi Compleet Maandabonnement',price:95.52,originalPrice:119.40,cat:'subscription',label:'20% abonnementvoordeel',img:'assets/products/zinergi-compleet-maandabonnement-v5.jpg',desc:'Iedere maand alle vier supplementen als papieren brievenbusnavulling: Biotica Expert, Fiber Expert, Magnesium Expert en Multi Compleet. Je bespaart â‚¬23,88 per maand en â‚¬286,56 per jaar.',badge:'Bespaar 20%',monthly:true},
{id:'leaky',name:'Leaky Gut darmonderzoek',price:159,cat:'onderzoek',label:'Onderzoek',img:'assets/products/leaky.webp',desc:'Gericht laboratoriumonderzoek dat inzicht geeft in de doorlaatbaarheid van de darmwand.'},
{id:'darmpakket',name:'Onderzoekspakket darmklachten',price:245,cat:'onderzoek',label:'Onderzoek',img:'assets/products/darmpakket.webp',desc:'Een verdiepend startpunt om oorzaken achter terugkerende darmklachten te onderzoeken.'},
{id:'hormoontest',name:'Oestrogeen metabolieten hormoontest',price:105,cat:'onderzoek',label:'Hormonen',img:'assets/products/hormoontest.webp',desc:'Krijg inzicht in hoe jouw lichaam oestrogenen verwerkt en uitscheidt.'},
{id:'consult',name:'Orthomoleculair 1e consult',price:150,cat:'traject',label:'Persoonlijke begeleiding',img:'assets/products/consult.webp',desc:'Een persoonlijk consult waarin klachten, voeding, leefstijl en eerdere uitslagen samenkomen.',badge:'Persoonlijk'},
{id:'resetdarmen',name:'Reset je Darmen',price:599,cat:'traject',label:'3 maanden',img:'assets/products/resetdarmen.webp',desc:'Een persoonlijk traject naar meer rust in je buik, betere vertering en duurzame energie.'},
{id:'ademreset',name:'Adem Reset Traject',price:650,cat:'traject',label:'Ademwerk',img:'assets/products/ademreset.webp',desc:'Zak uit je hoofd en herstel de verbinding met je lichaam en zenuwstelsel.'},
{id:'cacao',name:'Cacao, Adem & Opstelling',price:99,cat:'event',label:'6 september 2026',img:'assets/products/cacao.webp',desc:'Een bijzondere middag waarin cacao, verbonden ademhaling en familieopstellingen samenkomen.'},
{id:'familie',name:'Familieopstelling',price:99,cat:'event',label:'18 oktober 2026',img:'assets/products/familie.webp',desc:'Maak zichtbaar wat onder de oppervlakte speelt en laat beweging ontstaan waar het vastzit.'}
];
let filter='all',query='',sort='featured',cart=JSON.parse(localStorage.getItem('zinergi-cart-v2')||'[]');
const grid=document.getElementById('productGrid'),empty=document.getElementById('empty');
const money=n=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(n);
function visible(){let arr=products.filter(p=>(filter==='all'||p.cat===filter)&&p.name.toLowerCase().includes(query.toLowerCase()));if(sort==='low')arr.sort((a,b)=>a.price-b.price);if(sort==='high')arr.sort((a,b)=>b.price-a.price);if(sort==='az')arr.sort((a,b)=>a.name.localeCompare(b.name));return arr}
function render(){const arr=visible();document.getElementById('resultCount').textContent=`${arr.length} producten`;empty.style.display=arr.length?'none':'block';grid.innerHTML=arr.map(p=>{const action=p.subscriptionProduct?`data-subscription="${p.parentId}"`:p.variants?`data-detail="${p.id}"`:`data-add="${p.id}"`,actionText=p.subscriptionProduct?'Kies abonnement':p.monthly?'Neem maandabonnement':p.variants?'Kies verpakking':'Toevoegen aan tas',visual=p.gallery?`<div class="bundle-grid">${p.gallery.map((src,i)=>`<img src="${src}" alt="${p.name} navulling ${i+1}" loading="eager">`).join('')}</div>`:`<img src="${p.img}" alt="${p.name}" loading="eager">`;return `<article class="product ${p.id==='welkom'?'welcome-product':''} ${p.monthly?'monthly-product':''}"><div class="product-media" ${p.subscriptionProduct?`data-subscription="${p.parentId}"`:`data-detail="${p.id}"`}>${visual}${p.badge?`<span class="badge">${p.badge}</span>`:''}<button class="quick" ${p.subscriptionProduct?`data-subscription="${p.parentId}"`:`data-detail="${p.id}"`}>Bekijk opties</button></div><div class="product-info"><small>${p.variants?'Glazen startpot':p.label}</small><h3>${p.name}</h3><p>${p.originalPrice?`<s>${money(p.originalPrice)}</s> `:''}${money(p.price)}${p.subscriptionProduct?' per levering':p.monthly?' per maand':''}</p><button class="add" ${action}>${actionText} <span>+</span></button></div></article>`}).join('');bind()}
function bind(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=e=>{e.stopPropagation();add(b.dataset.add)});document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail));document.querySelectorAll('[data-subscription]').forEach(b=>b.onclick=e=>{e.stopPropagation();detail(b.dataset.subscription,'subscription')})}
function variantLabel(v,amount,frequency){if(v==='glass')return 'Eerste aankoop - glazen pot';if(v==='refill')return 'Eenmalige navulling - brievenbuszak';if(v==='subscription')return `Abonnement - ${amount} navulling${amount>1?'en':''} per ${frequency} weken`;return ''}
function add(id,variant='default',amount=1,frequency=''){const p=products.find(x=>x.id===id),key=[id,variant,amount,frequency].join('|'),line=cart.find(x=>x.key===key);if(line)line.qty++;else cart.push({key,id,variant,amount:Number(amount),frequency,qty:1,image:variant==='glass'?p.img:(variant==='refill'||variant==='subscription')?p.refillImg:p.img});save();openCart()}
function save(){localStorage.setItem('zinergi-cart-v2',JSON.stringify(cart));renderCart()}
function linePrice(x){const p=products.find(y=>y.id===x.id);return p.price*(x.amount||1)}
function renderCart(){document.getElementById('cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0);const wrap=document.getElementById('cartItems'),isEmpty=!cart.length;document.getElementById('cartEmpty').style.display=isEmpty?'block':'none';document.getElementById('cartFoot').style.display=isEmpty?'none':'block';wrap.innerHTML=cart.map(x=>{const p=products.find(y=>y.id===x.id),label=variantLabel(x.variant,x.amount,x.frequency);return `<div class="cart-row"><img src="${x.image||p.img}" alt=""><div><h4>${p.name}</h4>${label?`<small>${label}</small><br>`:''}<small>${x.qty} &times; ${money(linePrice(x))}</small><br><button data-remove="${x.key}">Verwijder</button></div><b>${money(linePrice(x)*x.qty)}</b></div>`}).join('');document.getElementById('cartTotal').textContent=money(cart.reduce((s,x)=>s+linePrice(x)*x.qty,0));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.key!==b.dataset.remove);save()})}
const cartEl=document.getElementById('cart'),overlay=document.getElementById('overlay');function openCart(){cartEl.classList.add('open');overlay.classList.add('open');cartEl.setAttribute('aria-hidden','false')}function closeCart(){cartEl.classList.remove('open');overlay.classList.remove('open');cartEl.setAttribute('aria-hidden','true')}
document.getElementById('cartToggle').onclick=openCart;document.getElementById('cartClose').onclick=closeCart;overlay.onclick=closeCart;
function variantPanel(p){return `<div class="purchase-options"><h3>Kies jouw manier</h3><label><input type="radio" name="purchase" value="glass" checked><span><b>Eerste aankoop</b><small>Herbruikbare glazen pot met bamboe deksel</small></span></label><label><input type="radio" name="purchase" value="refill"><span><b>Eenmalige navulling</b><small>Papieren zak met beschermfolie, past door de brievenbus</small></span></label><label><input type="radio" name="purchase" value="subscription"><span><b>Navulabonnement</b><small>Afgestemd op jouw hoeveelheid en gebruik</small></span></label><div class="subscription-settings" hidden><label>Hoeveelheid per levering<select id="subAmount"><option value="1">1 navulling</option><option value="2">2 navullingen</option><option value="3">3 navullingen</option></select></label><label>Levering iedere<select id="subFrequency"><option value="4">4 weken</option><option value="6">6 weken</option><option value="8">8 weken</option><option value="12">12 weken</option></select></label><p id="subPrice">${money(p.price)} per levering</p></div></div>`}
function detail(id,preferred='glass'){const p=products.find(x=>x.id===id),d=document.getElementById('productDialog');document.getElementById('productDetail').innerHTML=`<div class="detail"><img id="detailImage" src="${preferred==='subscription'?p.refillImg:p.img}" alt="${p.name}"><div class="detail-copy"><p class="eyebrow">${p.label}</p><h2>${p.name}</h2><p class="price">${p.originalPrice?`<s>${money(p.originalPrice)}</s> `:''}${money(p.price)}</p><p class="desc">${p.desc}</p>${p.variants?variantPanel(p):''}<button data-dialog-add="${p.id}">Toevoegen aan tas</button><ul>${p.variants?'<li>Glazen startpot is bedoeld voor de eerste aankoop</li><li>Navulzak met beschermfolie past door de brievenbus</li><li>Abonnement is instelbaar op hoeveelheid en gebruik</li>':'<li>Zorgvuldig geselecteerd door Zinergi</li><li>Persoonlijk advies mogelijk</li>'}<li>Veilig afrekenen via de bestaande shop</li></ul></div></div>`;d.showModal();if(p.variants){const radios=[...document.querySelectorAll('input[name="purchase"]')],settings=document.querySelector('.subscription-settings'),image=document.getElementById('detailImage'),amountEl=document.getElementById('subAmount'),priceEl=document.getElementById('subPrice'),updatePrice=()=>priceEl.textContent=`${money(p.price*Number(amountEl.value))} per levering`;radios.forEach(r=>r.onchange=()=>{settings.hidden=r.value!=='subscription';image.src=r.value==='glass'?p.img:p.refillImg});amountEl.onchange=updatePrice;if(preferred==='subscription'){const sub=radios.find(r=>r.value==='subscription');sub.checked=true;settings.hidden=false;updatePrice()}}document.querySelector('[data-dialog-add]').onclick=()=>{let variant='default',amount=1,frequency='';if(p.variants){variant=document.querySelector('input[name="purchase"]:checked').value;if(variant==='subscription'){amount=document.getElementById('subAmount').value;frequency=document.getElementById('subFrequency').value}}d.close();add(p.id,variant,amount,frequency)}}
document.querySelector('.dialog-close').onclick=()=>document.getElementById('productDialog').close();
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelector('[data-filter].active').classList.remove('active');b.classList.add('active');filter=b.dataset.filter;render()});document.getElementById('sort').onchange=e=>{sort=e.target.value;render()};
const searchbar=document.getElementById('searchbar');document.getElementById('searchToggle').onclick=()=>{searchbar.classList.add('open');document.getElementById('search').focus()};document.getElementById('searchClose').onclick=()=>searchbar.classList.remove('open');document.getElementById('search').oninput=e=>{query=e.target.value;render()};
render();renderCart();

