const products=[
{id:'biotica',name:'Biotica Expert',price:39.95,cat:'supplement',label:'Darmen',img:'assets/products/biotica-avena.webp',desc:'Probiotische ondersteuning voor een gevarieerd en veerkrachtig darmmicrobioom.',badge:'Bestseller'},
{id:'fiber',name:'Fiber Expert',price:32.50,cat:'supplement',label:'Darmen',img:'assets/products/fiber-avena.webp',desc:'Prebiotische vezels als dagelijkse voeding voor je goede darmbacteriën.'},
{id:'magnesium',name:'Magnesium Expert',price:19.95,cat:'supplement',label:'Energie & rust',img:'assets/products/magnesium-avena.webp',desc:'Ondersteunt ontspanning, spieren en een normale energiestofwisseling.',badge:'Populair'},
{id:'multi',name:'Multi Compleet',price:27,cat:'supplement',label:'Dagelijkse basis',img:'assets/products/multi-avena.webp',desc:'Een complete dagelijkse basis met zorgvuldig gekozen vitamines en mineralen.'},
{id:'leaky',name:'Leaky Gut darmonderzoek',price:159,cat:'onderzoek',label:'Onderzoek',img:'assets/products/leaky.webp',desc:'Gericht laboratoriumonderzoek dat inzicht geeft in de doorlaatbaarheid van de darmwand.'},
{id:'darmpakket',name:'Onderzoekspakket darmklachten',price:245,cat:'onderzoek',label:'Onderzoek',img:'assets/products/darmpakket.webp',desc:'Een verdiepend startpunt om oorzaken achter terugkerende darmklachten te onderzoeken.'},
{id:'hormoontest',name:'Oestrogeen metabolieten hormoontest',price:105,cat:'onderzoek',label:'Hormonen',img:'assets/products/hormoontest.webp',desc:'Krijg inzicht in hoe jouw lichaam oestrogenen verwerkt en uitscheidt.'},
{id:'consult',name:'Orthomoleculair 1e consult',price:150,cat:'traject',label:'Persoonlijke begeleiding',img:'assets/products/consult.webp',desc:'Een persoonlijk consult waarin klachten, voeding, leefstijl en eerdere uitslagen samenkomen.',badge:'Persoonlijk'},
{id:'resetdarmen',name:'Reset je Darmen',price:599,cat:'traject',label:'3 maanden',img:'assets/products/resetdarmen.webp',desc:'Een persoonlijk traject naar meer rust in je buik, betere vertering en duurzame energie.'},
{id:'ademreset',name:'Adem Reset Traject',price:650,cat:'traject',label:'Ademwerk',img:'assets/products/ademreset.webp',desc:'Zak uit je hoofd en herstel de verbinding met je lichaam en zenuwstelsel.'},
{id:'cacao',name:'Cacao, Adem & Opstelling',price:99,cat:'event',label:'6 september 2026',img:'assets/products/cacao.webp',desc:'Een bijzondere middag waarin cacao, verbonden ademhaling en familieopstellingen samenkomen.'},
{id:'familie',name:'Familieopstelling',price:99,cat:'event',label:'18 oktober 2026',img:'assets/products/familie.webp',desc:'Maak zichtbaar wat onder de oppervlakte speelt en laat beweging ontstaan waar het vastzit.'}
];
let filter='all',query='',sort='featured',cart=JSON.parse(localStorage.getItem('zinergi-cart')||'[]');
const grid=document.getElementById('productGrid'),empty=document.getElementById('empty');
const money=n=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(n);
function visible(){let arr=products.filter(p=>(filter==='all'||p.cat===filter)&&p.name.toLowerCase().includes(query.toLowerCase()));if(sort==='low')arr.sort((a,b)=>a.price-b.price);if(sort==='high')arr.sort((a,b)=>b.price-a.price);if(sort==='az')arr.sort((a,b)=>a.name.localeCompare(b.name));return arr}
function render(){const arr=visible();document.getElementById('resultCount').textContent=`${arr.length} producten`;empty.style.display=arr.length?'none':'block';grid.innerHTML=arr.map(p=>`<article class="product"><div class="product-media" data-detail="${p.id}"><img src="${p.img}" alt="${p.name}" loading="eager">${p.badge?`<span class="badge">${p.badge}</span>`:''}<button class="quick" data-detail="${p.id}">Snel bekijken</button></div><div class="product-info"><small>${p.label}</small><h3>${p.name}</h3><p>${money(p.price)}</p><button class="add" data-add="${p.id}">Toevoegen aan tas <span>＋</span></button></div></article>`).join('');bind()}
function bind(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=e=>{e.stopPropagation();add(b.dataset.add)});document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail))}
function add(id){const line=cart.find(x=>x.id===id);if(line)line.qty++;else cart.push({id,qty:1});save();openCart()}
function save(){localStorage.setItem('zinergi-cart',JSON.stringify(cart));renderCart()}
function renderCart(){document.getElementById('cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0);const wrap=document.getElementById('cartItems'),isEmpty=!cart.length;document.getElementById('cartEmpty').style.display=isEmpty?'block':'none';document.getElementById('cartFoot').style.display=isEmpty?'none':'block';wrap.innerHTML=cart.map(x=>{const p=products.find(y=>y.id===x.id);return `<div class="cart-row"><img src="${p.img}" alt=""><div><h4>${p.name}</h4><small>${x.qty} × ${money(p.price)}</small><br><button data-remove="${p.id}">Verwijder</button></div><b>${money(p.price*x.qty)}</b></div>`}).join('');document.getElementById('cartTotal').textContent=money(cart.reduce((s,x)=>s+products.find(p=>p.id===x.id).price*x.qty,0));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==b.dataset.remove);save()})}
const cartEl=document.getElementById('cart'),overlay=document.getElementById('overlay');function openCart(){cartEl.classList.add('open');overlay.classList.add('open');cartEl.setAttribute('aria-hidden','false')}function closeCart(){cartEl.classList.remove('open');overlay.classList.remove('open');cartEl.setAttribute('aria-hidden','true')}
document.getElementById('cartToggle').onclick=openCart;document.getElementById('cartClose').onclick=closeCart;overlay.onclick=closeCart;
function detail(id){const p=products.find(x=>x.id===id),d=document.getElementById('productDialog');document.getElementById('productDetail').innerHTML=`<div class="detail"><img src="${p.img}" alt="${p.name}"><div class="detail-copy"><p class="eyebrow">${p.label}</p><h2>${p.name}</h2><p class="price">${money(p.price)}</p><p class="desc">${p.desc}</p><button data-dialog-add="${p.id}">Toevoegen aan tas</button><ul><li>Zorgvuldig geselecteerd door Zinergi</li><li>Persoonlijk advies mogelijk</li><li>Veilig afrekenen via de bestaande shop</li></ul></div></div>`;d.showModal();document.querySelector('[data-dialog-add]').onclick=()=>{d.close();add(p.id)}}
document.querySelector('.dialog-close').onclick=()=>document.getElementById('productDialog').close();
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelector('[data-filter].active').classList.remove('active');b.classList.add('active');filter=b.dataset.filter;render()});document.getElementById('sort').onchange=e=>{sort=e.target.value;render()};
const searchbar=document.getElementById('searchbar');document.getElementById('searchToggle').onclick=()=>{searchbar.classList.add('open');document.getElementById('search').focus()};document.getElementById('searchClose').onclick=()=>searchbar.classList.remove('open');document.getElementById('search').oninput=e=>{query=e.target.value;render()};
render();renderCart();
